name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  BACKEND_RESOURCE_GROUP_NAME: "rg-sports-analytics-dev"
  BACKEND_STORAGE_ACCOUNT_NAME: "stsportsanalyticsnfcji2"
  BACKEND_STORAGE_CONTAINER_NAME: "tfstate"
  BACKEND_KEY: "terraform.tfstate"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform init -input=false \
            -backend-config="resource_group_name=${{ env.BACKEND_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ env.BACKEND_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ env.BACKEND_STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.BACKEND_KEY }}"

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color
        continue-on-error: true

      - name: Terraform Apply
        if: steps.plan.outcome == 'success'
        run: terraform apply -auto-approve -input=false
