name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    # --- THIS IS THE FIX ---
    # Set a default working directory for all steps in this job
    defaults:
      run:
        working-directory: ./terraform
    # ---------------------
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 'working-directory' is no longer needed here
      - name: Terraform Init
        run: terraform init

      # 'working-directory' is no longer needed here
      - name: Terraform Plan
        run: terraform plan -input=false

      # 'working-directory' is no longer needed here
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
```

### What's Changed:

I've added the `defaults` block. This tells GitHub Actions to run **all** `run:` commands in this job inside the `./terraform` folder. This is much cleaner and removes the three `working-directory` lines that were causing the syntax error.

### What to Do:

1.  Open the `.github/workflows/main.yml` file on your local machine.
2.  Replace its contents with the new code above.
3.  Commit and push the change:

    ```bash
    git add .github/workflows/main.yml
    git commit -m "Fix CI/CD with default working-directory"
    git push origin main
    

